system:
    configured_version: 0.9.1
    timezone: Europe/Sofia
    card_enabled: true
    cal_enabled: true
    dav_auth_type: Digest
    admin_passwordhash: f8db370cafadff867b67c54949fcd0cfffba52e040357e68c5861c0daccb210e
    failed_access_message: 'user %u authentication failure for Baikal'
    auth_realm: BaikalDAV
    base_uri: ''
    invite_from: ''
database:
    sqlite_file: /home/lux/mnt/data/Safe/Settings/.local/share/webdav/db.sqlite
    mysql: false
    mysql_host: ''
    mysql_dbname: ''
    mysql_username: ''
    mysql_password: ''
    encryption_key: d751622d3f5b43d8032d13953a13519b
